version: '3.8'

services:
  asp-net-core-redis:
    container_name: asp-net-core-redis
    image: aliyildizoz909/docker-demo-redis
    ports:
      - "5000:8080"
    depends_on:
      - redis-server   
  redis-server:
    container_name: redis-server
    image: redis
    ports:
      - "6379:6379"